[project]
name = "hosty"
version = "0.1.0"
description = "FastAPI app that returns the host header from the request"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"